### ISSUE TITLE
Инструкция по установке Home Assistant, Mosquitto (MQTT) и Zigbee2MQTT на VPS с Docker

### ISSUE THREAD

**Issue by makscrypto1983** [makscrypto1983/IOT-setup#3]
### Инструкция по установке Home Assistant, Mosquitto (MQTT) и Zigbee2MQTT на VPS с Docker

---

### Шаг 1: Подготовка VPS

1. **Обновите систему:**
   ```bash
   sudo apt update && sudo apt upgrade -y
   ```

2. **Установите Docker и Docker Compose:**
   ```bash
   sudo apt install docker.io docker-compose -y
   ```

3. **Добавьте текущего пользователя в группу `docker`:**
   ```bash
   sudo usermod -aG docker $USER
   ```
   После этого перезайдите в систему или выполните:
   ```bash
   newgrp docker
   ```

---

### Шаг 2: Установка Home Assistant

1. **Создайте папку для Home Assistant:**
   ```bash
   mkdir -p ~/homeassistant && cd ~/homeassistant
   ```

2. **Создайте файл `docker-compose.yml`:**
   ```bash
   nano docker-compose.yml
   ```

3. **Добавьте в файл следующий код:**
   ```yaml
   version: '3'
   services:
     homeassistant:
       container_name: homeassistant
       image: ghcr.io/home-assistant/home-assistant:stable
       volumes:
         - ./config:/config
       ports:
         - "8123:8123"
       restart: unless-stopped
   ```

4. **Запустите Home Assistant:**
   ```bash
   docker-compose up -d
   ```

5. **Откройте Home Assistant в браузере:**
   Перейдите по адресу `http://<IP_адрес_вашего_сервера>:8123`.

---

### Шаг 3: Установка Mosquitto (MQTT)

1. **Добавьте Mosquitto в файл `docker-compose.yml`:**
   Откройте файл `docker-compose.yml`:
   ```bash
   nano ~/homeassistant/docker-compose.yml
   ```

   Добавьте сервис Mosquitto:
   ```yaml
     mosquitto:
       container_name: mosquitto
       image: eclipse-mosquitto
       ports:
         - "1883:1883"
         - "9001:9001"
       volumes:
         - ./mosquitto/config:/mosquitto/config
         - ./mosquitto/data:/mosquitto/data
         - ./mosquitto/log:/mosquitto/log
       restart: unless-stopped
   ```

2. **Создайте папки и конфигурацию Mosquitto:**
   ```bash
   mkdir -p ~/homeassistant/mosquitto/{config,data,log}
   nano ~/homeassistant/mosquitto/config/mosquitto.conf
   ```

   Вставьте следующее:
   ```txt
   allow_anonymous false
   password_file /mosquitto/config/passwordfile
   ```

3. **Создайте файл паролей:**
   ```bash
   docker-compose up -d mosquitto
   docker exec -it mosquitto mosquitto_passwd -c /mosquitto/config/passwordfile <username>
   ```
   Замените `<username>` на желаемое имя пользователя. Укажите пароль, когда система запросит.

4. **Перезапустите контейнер:**
   ```bash
   docker-compose restart mosquitto
   ```

---

### Шаг 4: Установка Zigbee2MQTT

1. **Добавьте Zigbee2MQTT в файл `docker-compose.yml`:**
   Откройте файл `docker-compose.yml`:
   ```bash
   nano ~/homeassistant/docker-compose.yml
   ```

   Добавьте сервис Zigbee2MQTT:
   ```yaml
     zigbee2mqtt:
       container_name: zigbee2mqtt
       image: koenkk/zigbee2mqtt
       volumes:
         - ./zigbee2mqtt/data:/app/data
       devices:
         - "/dev/ttyACM0:/dev/ttyACM0"  # Укажите путь к вашему Zigbee-адаптеру
       ports:
         - "8080:8080"
       restart: unless-stopped
       network_mode: host
   ```

2. **Создайте папку и настройте Zigbee2MQTT:**
   ```bash
   mkdir -p ~/homeassistant/zigbee2mqtt/data
   nano ~/homeassistant/zigbee2mqtt/data/configuration.yaml
   ```

   Пример конфигурации:
   ```yaml
   mqtt:
     base_topic: zigbee2mqtt
     server: 'mqtt://localhost'
     user: '<username>'
     password: '<password>'
   serial:
     port: /dev/ttyACM0  # Укажите правильный порт
   frontend:
     port: 8080
   ```

3. **Запустите контейнер Zigbee2MQTT:**
   ```bash
   docker-compose up -d
   ```

---

### Шаг 5: Интеграция в Home Assistant

1. **Добавьте интеграцию MQTT:**
   - Перейдите в Home Assistant → **Настройки → Устройства и сервисы → Добавить интеграцию**.
   - Выберите **MQTT** и введите данные для подключения:
     - Брокер: `localhost`
     - Имя пользователя и пароль: указанные при настройке Mosquitto.

2. **Добавьте устройства Zigbee:**
   - Включите режим подключения устройств в веб-интерфейсе Zigbee2MQTT: `http://<IP_адрес_вашего_сервера>:8080`.

---

### Шаг 6: Проверка и тестирование

1. **Проверьте логи контейнеров:**
   - Home Assistant:
     ```bash
     docker logs homeassistant
     ```
   - Mosquitto:
     ```bash
     docker logs mosquitto
     ```
   - Zigbee2MQTT:
     ```bash
     docker logs zigbee2mqtt
     ```

2. **Тестирование MQTT:**
   Подключитесь к Mosquitto:
   ```bash
   mosquitto_sub -h localhost -t zigbee2mqtt/# -u <username> -P <password>
   ```

3. **Проверьте подключенные устройства Zigbee через Zigbee2MQTT.**

---

###SH скрипт по установке

Сохраните скрипт в файл, например setup.sh, сделайте его исполняемым (chmod +x setup.sh) и запустите (./setup.sh).

#!/bin/bash

# Функция для ввода данных с проверкой пустого значения
prompt_input() {
    local prompt="$1"
    local var
    while true; do
        read -rp "$prompt" var
        if [ -n "$var" ]; then
            echo "$var"
            break
        else
            echo "Ошибка: значение не может быть пустым. Повторите ввод."
        fi
    done
}

# Запрос имени пользователя и пароля для MQTT
MQTT_USER=$(prompt_input "Введите имя пользователя для MQTT: ")
MQTT_PASS=$(prompt_input "Введите пароль для MQTT: ")

# Обновление системы
echo "[1/6] Обновление системы..."
sudo apt update && sudo apt upgrade -y

# Установка Docker и Docker Compose
echo "[2/6] Установка Docker и Docker Compose..."
sudo apt install -y docker.io docker-compose
sudo usermod -aG docker $USER

# Создание папки для Home Assistant
mkdir -p ~/homeassistant && cd ~/homeassistant

# Создание docker-compose.yml
cat > docker-compose.yml <<EOL
version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - ./config:/config
    ports:
      - "8123:8123"
    restart: unless-stopped

  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    restart: unless-stopped

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
      - ./zigbee2mqtt/data:/app/data
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0" # Укажите правильный порт Zigbee
    ports:
      - "8080:8080"
    restart: unless-stopped
    network_mode: host
EOL

# Создание папок для Mosquitto и Zigbee2MQTT
mkdir -p mosquitto/{config,data,log} zigbee2mqtt/data

# Конфигурация Mosquitto
cat > mosquitto/config/mosquitto.conf <<EOL
allow_anonymous false
password_file /mosquitto/config/passwordfile
EOL

# Настройка паролей для MQTT
echo "[3/6] Настройка пользователя и пароля для Mosquitto..."
sudo docker-compose up -d mosquitto
sudo docker exec mosquitto mosquitto_passwd -c /mosquitto/config/passwordfile $MQTT_USER
sudo docker-compose restart mosquitto

# Настройка Zigbee2MQTT
cat > zigbee2mqtt/data/configuration.yaml <<EOL
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://localhost'
  user: '$MQTT_USER'
  password: '$MQTT_PASS'
serial:
  port: /dev/ttyACM0
frontend:
  port: 8080
EOL

# Запуск всех контейнеров
echo "[4/6] Запуск Home Assistant, Mosquitto и Zigbee2MQTT..."
docker-compose up -d

# Вывод информации о доступе
echo "[5/6] Установка завершена. Используйте следующие данные для подключения:"
echo "Home Assistant: http://<IP_адрес_вашего_сервера>:8123"
echo "MQTT Broker: mqtt://localhost:1883"
echo "Имя пользователя MQTT: $MQTT_USER"
echo "Пароль MQTT: $MQTT_PASS"
echo "Zigbee2MQTT интерфейс: http://<IP_адрес_вашего_сервера>:8080"

# Завершение
echo "[6/6] Перезапустите систему или выполните 'newgrp docker', чтобы применить изменения."
